### This workflow triggers automatically whenever code is pushed to the repository

name: Print My Name Workflow 

on: [push] 

jobs:
say-hello:
runs-on: ubuntu-latest
steps:
- name: Output name to the console
run: echo "Hello! My name is John Doe."
